name: my_movie_box
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  intl_generator: ^0.4.1
  cached_network_image: ^3.3.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  chopper: ^7.4.0
  equatable: ^2.0.5
  floor: ^1.5.0
  flutter_hooks: ^0.20.5
  pull_to_refresh: ^2.0.0
  logger: ^2.3.0
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  # cached_video_player: ^2.0.4
  #retrofit: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  chopper_generator: ^7.4.0
  floor_generator: ^1.4.2
  #retrofit_generator: ^8.1.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

